# toDo: strip defaults

Orderers:
  # unique name
  orderer-01:
    # node-type: orderer|peer
    Type: orderer
    # fabric overrides. everything below here will get applied to the
    # fabric binary on network  startup. see the orderer.yaml to see
    # what config is possible. the format here is the exact same as the
    # orderer.yaml (it's meant to  literally override that yaml)
    Config:
      Operations:
        ListenAddress: 127.0.0.1:6050

Peers:
  # unique name
  peer-01:
    Type: peer
    Config:


# Configuration for the configtxgen fabric binary.
# Creates system-channel and genesis block.
Configtxgen:
  FabricBinary: configtxgen # toDo: make default
  ScriptPath: create-consortium # toDo: make default and change to ScriptName
  ConfigPath: "." # toDo: make default
  # Must match a profile listed in the configtx.yaml
  Profile: "TwoOrgsOrdererGenesis"
  ChannelID: "system-channel"
  Output: "system-genesis-block/genesis.block" # todo: make default
  Config:
    Organizations:
      - &OrdererOrg
        Name: Ryan

    
